// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlvtm67g1eMaLmgEFd0MZ1i4aYmA_4DDA',
    appId: '1:1066829548492:web:a356068875c947350bab69',
    messagingSenderId: '1066829548492',
    projectId: 'madad-b4ef3',
    authDomain: 'madad-b4ef3.firebaseapp.com',
    databaseURL: 'https://madad-b4ef3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madad-b4ef3.firebasestorage.app',
    measurementId: 'G-W9SE1TL9TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzGv_cUkCMVy_VHCxn8hUzMtsDBRUOgE',
    appId: '1:1066829548492:android:904ed25dd712257c0bab69',
    messagingSenderId: '1066829548492',
    projectId: 'madad-b4ef3',
    databaseURL: 'https://madad-b4ef3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madad-b4ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjppcgX55OF_ZozHKlJIrkFMkjBqgX_Ss',
    appId: '1:1066829548492:ios:58db24b5dc4b92880bab69',
    messagingSenderId: '1066829548492',
    projectId: 'madad-b4ef3',
    databaseURL: 'https://madad-b4ef3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madad-b4ef3.firebasestorage.app',
    iosBundleId: 'com.example.madadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjppcgX55OF_ZozHKlJIrkFMkjBqgX_Ss',
    appId: '1:1066829548492:ios:58db24b5dc4b92880bab69',
    messagingSenderId: '1066829548492',
    projectId: 'madad-b4ef3',
    databaseURL: 'https://madad-b4ef3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madad-b4ef3.firebasestorage.app',
    iosBundleId: 'com.example.madadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlvtm67g1eMaLmgEFd0MZ1i4aYmA_4DDA',
    appId: '1:1066829548492:web:f6a30e7c7f6ef0660bab69',
    messagingSenderId: '1066829548492',
    projectId: 'madad-b4ef3',
    authDomain: 'madad-b4ef3.firebaseapp.com',
    databaseURL: 'https://madad-b4ef3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madad-b4ef3.firebasestorage.app',
    measurementId: 'G-JVG2276K69',
  );
}
